#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FRONTEND_DIR="$ROOT_DIR/frontend"
SNAPSHOT_PATH="$FRONTEND_DIR/public/data/vercel_snapshot.json"
SNAPSHOT_IMAGES_DIR="$FRONTEND_DIR/public/data/artist_images"
BUNDLE_DIR="$ROOT_DIR/vercel_app"

echo "[1/4] Export snapshot from SQLite"
python3 "$ROOT_DIR/scripts/export_vercel_snapshot.py" \
  --db "$ROOT_DIR/db/fantasanremo.db" \
  --output "$SNAPSHOT_PATH"

echo "[2/4] Cache artist images locally for fast standalone rendering"
python3 "$ROOT_DIR/scripts/cache_snapshot_images.py" \
  --snapshot "$SNAPSHOT_PATH" \
  --output-dir "$SNAPSHOT_IMAGES_DIR"

echo "[3/4] Build frontend in standalone mode (VITE_API_MODE=local)"
cd "$FRONTEND_DIR"
npm run build:standalone

echo "[4/4] Prepare vercel_app package"
if [ -d "$BUNDLE_DIR/.git" ]; then
  find "$BUNDLE_DIR" -mindepth 1 -maxdepth 1 ! -name ".git" -exec rm -rf {} +
else
  rm -rf "$BUNDLE_DIR"
  mkdir -p "$BUNDLE_DIR"
fi
cp -R "$FRONTEND_DIR/dist"/. "$BUNDLE_DIR"/
cp "$FRONTEND_DIR/vercel.json" "$BUNDLE_DIR/vercel.json"

cat > "$BUNDLE_DIR/README.md" <<'EOF'
# Vercel Standalone Package

This folder is generated by `scripts/prepare_vercel_bundle.sh`.

It contains only static assets ready for deploy, without backend code.
EOF

echo "Bundle ready at: $BUNDLE_DIR"
